disabled_rules:
  - trailing_whitespace
  - line_length
  - todo

opt_in_rules:
  - empty_count

included:
  - Sources

excluded:
  - Tests
  - .build

line_length:
  warning: 120
  error: 150

type_name:
  min_length: 2
  max_length: 40
