disabled_rules:
  - trailing_whitespace
  - line_length

opt_in_rules:
  - empty_count
  - missing_docs

included:
  - Sources

excluded:
  - Tests
  - .build

line_length:
  warning: 120
  error: 150
